/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  HealthChecks: () => import('#controllers/health_checks_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
